# Generated by Django 4.1.3 on 2022-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('user_email', models.CharField(max_length=300)),
                ('user_zipcode', models.CharField(max_length=300)),
                ('user_city', models.CharField(max_length=300)),
                ('user_state', models.CharField(max_length=300)),
                ('user_address', models.CharField(max_length=300)),
                ('html_format', models.CharField(max_length=300)),
                ('plain_text', models.CharField(max_length=300)),
            ],
        ),
    ]
