# Generated by Django 4.1.3 on 2022-11-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_submit', '0003_form_data_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='FORM_DATA_FROM_USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('user_email', models.CharField(max_length=300)),
                ('user_zipcode', models.CharField(max_length=300)),
                ('user_city', models.CharField(max_length=300)),
                ('user_state', models.CharField(max_length=300)),
                ('user_address', models.CharField(max_length=300)),
                ('mobile_number', models.CharField(max_length=300)),
                ('whatsapp_number', models.CharField(max_length=300)),
                ('distributor', models.CharField(max_length=300)),
                ('counter_type', models.CharField(max_length=300)),
                ('electricity_consumption', models.CharField(max_length=300)),
                ('surface_ownership', models.CharField(max_length=300)),
                ('type_of_roof', models.CharField(max_length=300)),
                ('user_interest', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Form_DATA',
        ),
        migrations.DeleteModel(
            name='Form_DATA_NEW',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
